version: "2"

services:
  gearman-server:
    image: artefactual/gearmand:latest
    ports:
      - 127.0.0.1:4730:4730
    networks:
      - app

  date-worker:
    image: artefactual/gearmand:latest
    command: gearman -h gearman-server -p 4730 -w -f date date
    depends_on:
      - gearman-server
    networks:
      - app

  ping-worker:
    image: artefactual/gearmand:latest
    user: root
    command: gearman -h gearman-server -p 4730 -w -f ping xargs ping -c 3
    depends_on:
      - gearman-server
    networks:
      - app

  stock-quote-worker:
    image: artefactual/gearmand:latest
    user: root
    command: gearman -h gearman-server -p 4730 -w -f stock-quote xargs /data/get-stock-quote.sh
    volumes:
      - ./bin:/data
    depends_on:
      - gearman-server
    networks:
      - app

networks:
  app:
    driver: "bridge"
